services:
  - type: web
    name: weather-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENWEATHER_API_KEY
        value: your_api_key_here
